"""
build_echarts_mapping.py — Build complete ISO3 ↔ ECharts world.json name mapping.

Output: frontend/src/lib/echartsCountries.ts với mapping cho 213+/217 quốc gia.
Tránh tình trạng quốc gia có trong API nhưng không hiển thị trên bản đồ.
"""
import json
import subprocess
from pathlib import Path

try:
    import pycountry
except ImportError:
    subprocess.check_call(["pip", "install", "-q", "pycountry"])
    import pycountry

ROOT = Path(__file__).resolve().parent.parent
WORLD_JSON = ROOT / "frontend" / "public" / "world.json"
OUT_TS = ROOT / "frontend" / "src" / "lib" / "echartsCountries.ts"

# Mapping thủ công cho các tên ECharts không match được pycountry fuzzy
MANUAL = {
    "United States of America": "USA", "Russia": "RUS", "Iran": "IRN",
    "Syria": "SYR", "South Korea": "KOR", "Korea": "KOR", "Dem. Rep. Korea": "PRK",
    "Vietnam": "VNM", "Laos": "LAO", "Lao PDR": "LAO", "Brunei": "BRN",
    "Moldova": "MDA", "Macedonia": "MKD", "North Macedonia": "MKD",
    "Kosovo": "XKX", "Palestine": "PSE", "Venezuela": "VEN", "Bolivia": "BOL",
    "Tanzania": "TZA", "Ivory Coast": "CIV",
    "Cape Verde": "CPV", "Swaziland": "SWZ", "Eswatini": "SWZ",
    "Burma": "MMR", "Myanmar": "MMR",
    "East Timor": "TLS", "Timor-Leste": "TLS",
    "Bahamas": "BHS", "Gambia": "GMB", "W. Sahara": "ESH",
    "Greenland": "GRL", "French Guiana": "GUF", "New Caledonia": "NCL",
    "Puerto Rico": "PRI", "Taiwan": "TWN", "Hong Kong": "HKG", "S. Sudan": "SSD",
    "Eq. Guinea": "GNQ", "Dominican Rep.": "DOM", "Bosnia and Herz.": "BIH",
    "Antigua and Barb.": "ATG", "Trinidad and Tobago": "TTO",
    "Saint Lucia": "LCA", "St. Vin. and Gren.": "VCT",
    "San Marino": "SMR", "Vatican": "VAT",
    "United Arab Emirates": "ARE", "Saudi Arabia": "SAU",
    "New Zealand": "NZL", "Sri Lanka": "LKA",
    "Costa Rica": "CRI", "El Salvador": "SLV",
    "Dem. Rep. Congo": "COD", "Congo": "COG",
    "United Kingdom": "GBR", "Turkey": "TUR", "Czech Rep.": "CZE",
    "Solomon Is.": "SLB", "Central African Rep.": "CAF",
    "Cayman Is.": "CYM", "N. Cyprus": "CYP", "Falkland Is.": "FLK",
    "Faeroe Is.": "FRO", "Heard I. and McDonald Is.": "HMD",
    "Br. Indian Ocean Ter.": "IOT", "Fr. S. Antarctic Lands": "ATF",
    "N. Mariana Is.": "MNP", "Fr. Polynesia": "PYF",
    "S. Geo. and S. Sandw. Is.": "SGS", "St. Pierre and Miquelon": "SPM",
    "Turks and Caicos Is.": "TCA", "U.S. Virgin Is.": "VIR",
    "Siachen Glacier": None,  # disputed
}


def main() -> None:
    with WORLD_JSON.open(encoding="utf-8") as f:
        geo = json.load(f)

    iso3_to_name: dict[str, str] = {}
    unmapped: list[str] = []

    for feat in geo["features"]:
        name = feat["properties"]["name"]
        # Skip features có name rỗng (vài đảo nhỏ không có tên trong GeoJSON)
        if not name or not name.strip():
            continue
        if name in MANUAL:
            iso3 = MANUAL[name]
            if iso3 is None:
                unmapped.append(name)
                continue
        else:
            try:
                iso3 = pycountry.countries.search_fuzzy(name)[0].alpha_3
            except (LookupError, IndexError):
                unmapped.append(name)
                continue
        # Không ghi đè entry đã có (ưu tiên ECharts name xuất hiện đầu tiên)
        if iso3 not in iso3_to_name:
            iso3_to_name[iso3] = name

    print(f"Mapped {len(iso3_to_name)} ISO3 -> ECharts names")
    print(f"Unmapped ({len(unmapped)}): {unmapped}")

    # Build TS file
    items = sorted(iso3_to_name.items())
    lines = [
        "// AUTO-GENERATED by scripts/build_echarts_mapping.py",
        "// Mapping ISO3 -> ECharts world.json display name (217 features).",
        "// Re-run script khi cập nhật world.json hoặc API trả ISO3 mới.",
        "",
        "export const ECHARTS_COUNTRY_NAMES: Record<string, string> = {",
    ]
    for iso3, name in items:
        # Quote-safe: ECharts names không có backslash hay double-quote ngoài Côte d'Ivoire
        # Dùng double-quoted string, escape backslash + double-quote
        esc = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  {iso3}: "{esc}",')
    lines.append("};")
    lines.append("")
    lines.append("// Reverse: ECharts name -> ISO3")
    lines.append("export const ISO3_BY_ECHARTS_NAME: Record<string, string> = Object.fromEntries(")
    lines.append("  Object.entries(ECHARTS_COUNTRY_NAMES).map(([iso3, name]) => [name, iso3]),")
    lines.append(");")
    lines.append("")

    OUT_TS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_TS}")


if __name__ == "__main__":
    main()
